### ISSUE TITLE
Problems trying to run in Python 3.32

### ISSUE THREAD

**Issue by hafizbistar** [sha256/python-var-dump#1]
I get this error when i try to run it

```
Traceback (most recent call last):
    File "D:\Project\Tyme Agent Py\src\main.py", line 4, in <module>
        from var_dump import var_dump
    File "D:\Python\lib\site-packages\var_dump\__init__.py", line 2, in <module>
        from _var_dump import var_dump
ImportError: No module named '_var_dump'
```

**Comment by theres1** [comment]
I have this error in 3.4.3 and I have this file right in the place.

**Comment by a904guy** [comment]
I've made appropriate fixes for py3+, https://github.com/sha256/python-var-dump/pull/10

@sha256, if you can :+1: this that would be awesome.

**Comment by a904guy** [comment]
@sha256, sorry forgot this change as well, https://github.com/sha256/python-var-dump/pull/11
